
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('rooms').del()
    .then(function () {
      // Inserts seed entries
      return knex('rooms').insert([
        {
          id: 1000000,
          landlord_id: 1000001,
          street: '2315 Brunswick St',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1000,
          deposit_amount: 500,
          available_date: '2018/03/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: 49.264254,
          lng: -123.097665
        },
        {
          id: 1000001,
          landlord_id: 1000001,
          street: 'Mount Pleasant',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1000,
          deposit_amount: 500,
          available_date: '2018/03/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: false,
          storage: false,
          laundry_on_site: false,
          furniture: true,
          parking: true,
          details: null,
          lng: -123.104124,
          lat: 49.266416
        },
        {
          id: 1000002,
          landlord_id: 1000001,
          street: 'Downtown Vancouver',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1000,
          deposit_amount: 500,
          available_date: '2018/01/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lng: -123.117943,
          lat: 49.278747
        },
        {
          id: 1000003,
          landlord_id: 1000001,
          street: 'EB Beach Ave FS Hornby St',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/01/15',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lng: -123.132362,
          lat: 49.275147
        },
        {
          id: 1000004,
          landlord_id: 1000001,
          street: '128 west hastings st',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1000,
          deposit_amount: 600,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: 49.28184419999999,
          lng: -123.10816169999998
        },
        {
          id: 1000005,
          landlord_id: 1000001,
          street: '610 Granville Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1250,
          deposit_amount:475,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000006,
          landlord_id: 1000001,
          street: 'The Elaine, 3819 & 3921 Cambie Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/03/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000007,
          landlord_id: 1000001,
          street: '1133 Hornby Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000008,
          landlord_id: 1000001,
          street: '1001 Homer Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000009,
          landlord_id: 1000001,
          street: '2145 York Avenue',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000010,
          landlord_id: 1000001,
          street: 'Beresford Apartments, 1221 Homer Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000011,
          landlord_id: 1000001,
          street: 'Penderville Apartments, 1748 East Pender Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000012,
          landlord_id: 1000001,
          street: '2706 - 501 Pacific Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000013,
          landlord_id: 1000001,
          street: '1801 - 1295 Richards Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000014,
          landlord_id: 1000001,
          street: '1058 Cambie Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000015,
          landlord_id: 1000001,
          street: '1603 - 1055 Homer Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000016,
          landlord_id: 1000001,
          street: '1501 - 1252 Hornby',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000017,
          landlord_id: 1000001,
          street: '403 - 1102 Hornby Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000018,
          landlord_id: 1000001,
          street: '1133 - 933 Hornby Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000019,
          landlord_id: 1000001,
          street: '1802 - 788 Richards Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000020,
          landlord_id: 1000001,
          street: '702 - 1277 Nelson Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000021,
          landlord_id: 1000001,
          street: '707 - 822 Seymour Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000022,
          landlord_id: 1000001,
          street: '602 - 819 Hamilton Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date:'2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000023,
          landlord_id: 1000001,
          street: '221- 55 E. Cordova',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000024,
          landlord_id: 1000001,
          street: '210 - 55 E Cordova St',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000025,
          landlord_id: 1000001,
          street: '803 - 128 Cordova St W',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 3500,
          deposit_amount: 1500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000026,
          landlord_id: 1000001,
          street: '210 - 718 Main Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000027,
          landlord_id: 1000001,
          street: '1905 - 188 Keefer Place',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 3500,
          deposit_amount: 1500,
          available_date: '2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000028,
          landlord_id: 1000001,
          street: '1810 - 63 Keefer Place',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: false,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000029,
          landlord_id: 1000001,
          street: '605 - 633 Abbott St',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000030,
          landlord_id: 1000001,
          street: '210 - 718 Main Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000031,
          landlord_id: 1000001,
          street: '2306 - 888 Homer Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000032,
          landlord_id: 1000001,
          street: '2610 - 939 Expo Blvd',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: false,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000033,
          landlord_id: 1000001,
          street: '1702 - 928 Beatty Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: false,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000034,
          landlord_id: 1000001,
          street: '1058 Cambie St',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: false,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000035,
          landlord_id: 1000001,
          street: '710 - 1050 Burrard Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 3500,
          deposit_amount: 1500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000036,
          landlord_id: 1000001,
          street: '2102 - 1200 Alberni',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: false,
          internet: true,
          heat: false,
          natural_gas: false,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000037,
          landlord_id: 1000001,
          street: '3405-1111 W Pender',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: false,
          storage: true,
          laundry_on_site: false,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000038,
          landlord_id: 1000001,
          street: '2605 - 1077 West Cordova Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 3500,
          deposit_amount: 1500,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: false,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000039,
          landlord_id: 1000001,
          street: '2305 - 1166 Melville Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000040,
          landlord_id: 1000001,
          street: '2102 - 1200 Alberni',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: false,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000041,
          landlord_id: 1000001,
          street: '2302 - 1189 Melville',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: false,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000042,
          landlord_id: 1000001,
          street: '404 - 738 Broughton',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 3500,
          deposit_amount: 1500,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000043,
          landlord_id: 1000001,
          street: '2201 - 1420 West Georgia Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: false,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000044,
          landlord_id: 1000001,
          street: '902 - 560 Cardero',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: false,
          eletricity: false,
          internet: true,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000045,
          landlord_id: 1000001,
          street: '1603 - 1723 Alberni Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000046,
          landlord_id: 1000001,
          street: '103 - 1860 Robson Street',
          city: 'Vancouver',
          pet_friendly: true,
          rent_amount: 2500,
          deposit_amount: 1000,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000047,
          landlord_id: 1000001,
          street: '9A - 1500 Alberni Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 3500,
          deposit_amount: 1500,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: false,
          heat: false,
          natural_gas: true,
          storage: false,
          laundry_on_site: false,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000048,
          landlord_id: 1000001,
          street: '1506 - 1420 West Georgia Street',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: true,
          storage: false,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000049,
          landlord_id: 1000001,
          street: '303 - 717 Jervis St',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: false,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: false,
          furniture: true,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000050,
          landlord_id: 1000001,
          street: '2102 - 1239 W Georgia St',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 2000,
          deposit_amount: 750,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: false,
          heat: true,
          natural_gas: false,
          storage: true,
          laundry_on_site: false,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000051,
          landlord_id: 1000001,
          street: '2302 - 1189 Melville',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: true,
          parking: false,
          details: null,
          lat: null,
          lng: null
        },
        {
          id: 1000052,
          landlord_id: 1000001,
          street: '3405-1111 W Pender',
          city: 'Vancouver',
          pet_friendly: false,
          rent_amount: 1500,
          deposit_amount: 500,
          available_date: '2018/02/01',
          water: true,
          eletricity: true,
          internet: true,
          heat: true,
          natural_gas: true,
          storage: true,
          laundry_on_site: true,
          furniture: false,
          parking: true,
          details: null,
          lat: null,
          lng: null
        },
      ])
    });
};
